/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCompareRouteImport } from './routes/api/compare'
import { Route as DocDocIdRouteImport } from './routes/doc.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareRoute = ApiCompareRouteImport.update({
  id: '/api/compare',
  path: '/api/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DocDocIdRoute = DocDocIdRouteImport.update({
  id: '/doc/$docId',
  path: '/doc/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/compare': typeof ApiCompareRoute
  '/doc/$docId': typeof DocDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/compare': typeof ApiCompareRoute
  '/doc/$docId': typeof DocDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/compare': typeof ApiCompareRoute
  '/doc/$docId': typeof DocDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/compare'
    | '/guide'
    | '/api/analyze'
    | '/api/chat'
    | '/api/compare'
    | '/doc/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/compare'
    | '/guide'
    | '/api/analyze'
    | '/api/chat'
    | '/api/compare'
    | '/doc/$docId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/compare'
    | '/guide'
    | '/api/analyze'
    | '/api/chat'
    | '/api/compare'
    | '/doc/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  GuideRoute: typeof GuideRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCompareRoute: typeof ApiCompareRoute
  DocDocIdRoute: typeof DocDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare': {
      id: '/api/compare'
      path: '/api/compare'
      fullPath: '/api/compare'
      preLoaderRoute: typeof ApiCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$docId': {
      id: '/doc/$docId'
      path: '/doc/$docId'
      fullPath: '/doc/$docId'
      preLoaderRoute: typeof DocDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  GuideRoute: GuideRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCompareRoute: ApiCompareRoute,
  DocDocIdRoute: DocDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
